### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by rshagiev** [filodex/Binance-p2p-Arbs-Tracker#1]
Hello. Managed to fix an error with puppeteer on ARM but am getting errors after launch 

TimeoutError: waiting for selector `#__APP > div.layout__Container-sc-1v4mjny-0.hFTMle.scroll-container > main > div.css-186r813 > div > div.css-vurnku` failed: timeout 30000ms exceeded
    at new WaitTask (/home/pi/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34)
    at DOMWorld.waitForSelectorInPage (/home/pi/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26)
    at Object.internalHandler.waitFor (/home/pi/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/home/pi/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29)
    at Frame.waitForSelector (/home/pi/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:942:51)
    at Page.waitForSelector (/home/pi/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2370:33)
    at getUsdtRubOffers (file:///home/pi/node_modules/binancep2parbs/src/puppeteer.js:175:16)
    at Module.getPricesOfAllTradingPairs (file:///home/pi/node_modules/binancep2parbs/src/puppeteer.js:29:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///home/pi/node_modules/binancep2parbs/src/binanceArbs.js:68:31)
pricesIfSllTrading Pairs undefined
file:///home/pi/node_modules/binancep2parbs/src/binanceArbs.js:122
        (startValue / prices.usdtRub_bestOffer.price) *
                             ^

TypeError: Cannot read properties of undefined (reading 'usdtRub_bestOffer')
    at calcTradesProfit (file:///home/pi/node_modules/binancep2parbs/src/binanceArbs.js:122:30)
    at main (file:///home/pi/node_modules/binancep2parbs/src/binanceArbs.js:72:24)
    at async file:///home/pi/node_modules/binancep2parbs/src/binanceArbs.js:24:1

**Comment by rshagiev** [comment]
Проблема возникает при загрузке оферов с бинанса. Прогружается пустая страница p2p и выкидывается после timout. 
![image](https://user-images.githubusercontent.com/15612502/169802052-0642ed7e-3cb8-445e-a587-a45c57cb1f13.png)

**Comment by filodex** [comment]
Я, чтобы не бороться с непостоянством бинанса - просто запускаю всё это дело при помощи pm2. И там уже при вылете просто автоперезапуском все лечится.

Но я попробую исправить это, если мозгов хватит.
